novosga:
  build: .
  ports:
   - "81:81"
   - "443:443"

  links:
   - db

db:
  image: mysql:5.7
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=phprs
   - MYSQL_DATABASE=phprs